// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARHWSmZtEhMaB-VCPOIY3qwsDIBxBattw',
    appId: '1:641459946821:web:c4dc1efab1ba23e129ea2c',
    messagingSenderId: '641459946821',
    projectId: 'flutter-login-register-ae7c8',
    authDomain: 'flutter-login-register-ae7c8.firebaseapp.com',
    storageBucket: 'flutter-login-register-ae7c8.appspot.com',
    measurementId: 'G-J73H6PDXRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoHXI1mlg33jw3rpshxXYU-kb7X3xfYdk',
    appId: '1:641459946821:android:75db68638a040e6229ea2c',
    messagingSenderId: '641459946821',
    projectId: 'flutter-login-register-ae7c8',
    storageBucket: 'flutter-login-register-ae7c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzLqqG4XrSf7AteiObLAhCD9HzonX3bBo',
    appId: '1:641459946821:ios:27342828f9b464cb29ea2c',
    messagingSenderId: '641459946821',
    projectId: 'flutter-login-register-ae7c8',
    storageBucket: 'flutter-login-register-ae7c8.appspot.com',
    iosClientId: '641459946821-42lraj3p2e6rllh33jp5n9mkavvhsldr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzLqqG4XrSf7AteiObLAhCD9HzonX3bBo',
    appId: '1:641459946821:ios:27342828f9b464cb29ea2c',
    messagingSenderId: '641459946821',
    projectId: 'flutter-login-register-ae7c8',
    storageBucket: 'flutter-login-register-ae7c8.appspot.com',
    iosClientId: '641459946821-42lraj3p2e6rllh33jp5n9mkavvhsldr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginSignup',
  );
}
